version: '3'

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24

services:

  # MongoDB and document data store
  init:
    container_name: init
    image: erratik/kusanagi-init
    restart: always
    environment:
      - MONGO_LOCAL_STORAGE=/Users/erratik/Sites/_mongod/data
    networks:
      mongo_net:
        ipv4_address: 172.16.0.2
    ports:
      - "27017:27017"
    command: ./run.sh


  mongo_backup:
    container_name: mongo_backup
    image: mongo
    depends_on:
      - init
    networks:
      mongo_net:
    volumes:
      - mongo:/data/heroku_10tzj082
    command: mongodump --db datawhore -u erratik -p kaya80ate /data
    # command: ./run.sh

  mongo_restore:
    container_name: mongo_restore
    image: mongo
    depends_on:
      - init
      - mongo_backup
    networks:
      mongo_net:
    volumes:
      - mongo:/data/heroku_10tzj082
    command: mongorestore --host=172.16.0.2 --db datawhore -u erratik -p kaya80ate /data/heroku_10tzj082

  # Distributed in-memory cache
  redis:
    image: redis:4.0.6-alpine
    read_only: true
    networks:
      mongo_net:
    links:
      - mongo_backup
    volumes:
      - redis:/data
    user: redis


  # Data API and authentication/authorization
  api:
    image: api
    build:
      context: ./
      args:
        NODE_ENV: test
    restart: always
    hostname: localhost
    networks:
      mongo_net:
    links:
      - init
    depends_on:
      - init
      - mongo_restore
      - redis
    environment:
      - CORS_ORIGIN=http://localhost:8080
      - PORT=10010
      - HOSTNAME=localhost
      - DATABASE_URL=mongodb://erratik:kaya80ate@172.16.0.2/datawhore
      - MONGO_LOCAL_STORAGE=/Users/erratik/Sites/_mongod/data
      - REDIS_URL=redis://redis:6379/0
      - SESSION_SECRET=wZjwhFtzQsd7r87W6AZw45Sm
      # - FACEBOOK_ID=${FACEBOOK_DEV_APPID}
      # - FACEBOOK_SECRET=${FACEBOOK_DEV_APPSECRET}
      # - GOOGLE_ID=xxxxx.apps.googleusercontent.com
      # - GOOGLE_SECRET=xxxxx
      # - TWITTER_KEY=xxxxx
      # - TWITTER_SECRET=xxxxx
    ports:
      - "10010:10010"
      - "127.0.0.1:9229:9229" # V8 inspector for tools/run.js
      - "127.0.0.1:9230:9230" # V8 inspector for src/server.js
    volumes:
      - yarn:/home/node/.cache/yarn
      - ./build:/usr/src/app/build
      - ./locales:/usr/src/app/locales
      - ./migrations:/usr/src/app/migrations
      - ./seeds:/usr/src/app/seeds
      - ./src:/usr/src/app/src
      - ./tools:/usr/src/app/tools
      - ./.babelrc:/usr/src/app/.babelrc
      - ./.eslintrc.js:/usr/src/app/.eslintrc.js
      - ./.gitignore:/usr/src/app/.gitignore
      - ./.prettierrc:/usr/src/app/.prettierrc
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
    # command: "node tools/run.js" # or, `node --inspect=0.0.0.0:9229 tools/run.js`
    command: node --inspect=0.0.0.0:9229 tools/run.js


volumes:
  redis:
  mongo:
  init:
  yarn:

