FROM mongo:3.2.10

ENV AUTH yes
ENV STORAGE_ENGINE wiredTiger
ENV JOURNALING yes

# ENV MONGO_STORAGE_PATH_LOCAL MONGO_STORAGE_PATH_LOCAL
# ENV MONGODB_APPLICATION_DATABASE MONGODB_APPLICATION_DATABASE
# ENV MONGODB_APPLICATION_USER MONGODB_APPLICATION_USER
# ENV MONGODB_APPLICATION_PASS MONGODB_APPLICATION_PASS

ENV MONGO_LOCAL_STORAGE "/Users/erratik/Sites/_mongod/data"
ENV MONGODB_APPLICATION_DATABASE "datawhore"
ENV MONGODB_APPLICATION_USER "erratik"
ENV MONGODB_APPLICATION_PASS "kaya80ate"

ADD run.sh /run.sh
ADD set_mongodb_password.sh /set_mongodb_password.sh

EXPOSE 27017
# RUN ["/bin/bash", "-c", "mkdir /tachikoma"]
CMD ["/run.sh"]
